name = "toniolab"
main = ".open-next/worker.js"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "iwasaki-phrases"
database_id = "f4801cde-0f1d-4bc9-beec-5d8709813798"
